FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_SYSTEM_PYTHON=1
ENV UV_COMPILE_BYTECODE=1
# Disable development dependencies
ENV UV_NO_DEV=1

RUN uv python install --compile-bytecode
RUN uv sync --compile-bytecode
